# Generated by Django 6.0.4 on 2026-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='credential',
            name='credential_type',
            field=models.CharField(choices=[('password', '密码'), ('wechat', '微信'), ('email', '邮箱')], max_length=20),
        ),
    ]
